apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: App-lb
  annotations:
    kubernetes.io/ingress.class: internal-lb
spec:
  rules:
    - host: 
      http:
        paths:
          - backend:
              serviceName: APP
              servicePort: 80
            path: /

